[package]
name = "websocket-logger"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
hex = "0.4.3"
futures-util = "0.3.31"
